name: Build Python Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m virtualenv .venv
        .venv\Scripts\activate
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        .venv\Scripts\activate
        pyinstaller --name "Memory Management Simulator" --windowed --onefile main.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: Memory Management Simulator
        path: dist/Memory Management Simulator.exe
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download executable artifact
      uses: actions/download-artifact@v4
      with:
        name: Memory Management Simulator

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Memory Management Simulator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
